// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuItF-U8ojyA0ZivmzwGbrBSsOvYaWoY',
    appId: '1:838987827184:web:dfb634692c1eda9dbe7f35',
    messagingSenderId: '838987827184',
    projectId: 'factoryapp-firebase',
    authDomain: 'factoryapp-firebase.firebaseapp.com',
    databaseURL: 'https://factoryapp-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-firebase.appspot.com',
    measurementId: 'G-48L6YWV2GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHSTH5yqQpTJzNYml6Wzbx_A8mrgqEp6A',
    appId: '1:838987827184:android:8fce05a0a15296d7be7f35',
    messagingSenderId: '838987827184',
    projectId: 'factoryapp-firebase',
    databaseURL: 'https://factoryapp-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJ-iznaPX-khncJZKYcLP_tPegbaKlco',
    appId: '1:838987827184:ios:e23ae39278c186bcbe7f35',
    messagingSenderId: '838987827184',
    projectId: 'factoryapp-firebase',
    databaseURL: 'https://factoryapp-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-firebase.appspot.com',
    iosClientId: '838987827184-hq6r45p2ipvlq6sjkdd3mgld67s599g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJ-iznaPX-khncJZKYcLP_tPegbaKlco',
    appId: '1:838987827184:ios:e403dbc038476f66be7f35',
    messagingSenderId: '838987827184',
    projectId: 'factoryapp-firebase',
    databaseURL: 'https://factoryapp-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'factoryapp-firebase.appspot.com',
    iosClientId: '838987827184-a279mpka1vnonkjdmapcs6qui24arc6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.factoryapp',
  );
}
